### ISSUE TITLE
How to build TorWall in Windows?

### ISSUE THREAD

**Issue by dehghani-mehdi** [basil00/TorWall#20]
Hi,

I followed build instruction in README, when I run `build.sh`, the zip files got extract, but that's it, nothing else happens.

Would you explain more about build TorWall in Windows?

**Comment by basil00** [comment]
Only Linux cross compilation is "officially" supported.  It might be possible to build on Windows using MSYS but I've never tried.

**Comment by dehghani-mehdi** [comment]
@basil00 would you turn on some lights about doing that?

**Comment by basil00** [comment]
Basically, you'll need to install MSYS, open a console, extract and goto the source directory, extract the necessary dependencies (WinDivert, Tor), then run `make` (& fix any make errors).  Building the install `exe` requires `nsis` which may or may not be supported (I can't remember).

From experience, maintaining multiple build envs is a pain and I prefer Linux so that's what is "officially" supported.  This doesn't affect most users who are happy to just d/l the pre-built `exe`.

**Comment by SEODEMON** [comment]
Please rebuild and update version 1.2
