### ISSUE TITLE
doesnt work, says intercept but does nothing

### ISSUE THREAD

**Issue by cerberii** [basil00/TorWall#5]
Doesnt work, seems there is some kind of DNS problem with your project

```
ntercept DNS raw.githubusercontent.com
Intercept DNS raw.githubusercontent.com
Intercept DNS duckduckgo.com
Intercept DNS raw.githubusercontent.com
Intercept DNS duckduckgo.com
Intercept DNS clients4.google.com
Intercept DNS duckduckgo.com
Intercept DNS clients4.google.com
Intercept DNS raw.githubusercontent.com
Intercept DNS clients4.google.com
Intercept DNS duckduckgo.com
Intercept DNS clients4.google.com
Intercept DNS raw.githubusercontent.com
Intercept DNS duckduckgo.com
Intercept DNS clients4.google.com
Intercept DNS google.com
Intercept DNS google.com
Intercept DNS google.com
Tor divert STOP
Flush DNS cache
Tor divert is OFF...
```

**Comment by basil00** [comment]
The `Intercept` messages are to be expected in normal operation.  Tallow does this to redirect the application (e.g. web browser) to the Tor network.

The problem is likely that Tor itself is not working properly for some reason.  Sometimes it can take a few minutes after pressing the button to get going.  Restarting your browser can sometimes help.  Tor itself may be slow if you are unlucky.

If it is still not working, it is usually some other problem, e.g., if Tor traffic is blocked by your ISP/network.

**Comment by cerberii** [comment]
tor itself works fine.  im thinking its a dns routing issue with the
program.  I did not leave it for very long.  How long do you need to leave
it on to see if it works?  I left it on for 5 minutes or so.  It shows it
bootstraps and looks like everything is functioning.  The only problem I
suspect , as with middleboxes, is a DNS routing issue that is not handled
properly.
